[Profile]
Name = "Alex Navia"
JobTitle = "Desarrollador de Software"
Bio = "Apasionado de crear increíbles experiencias web. Disfruto de convertir ideas en realidad. Tengo experiencia trabajando con JavaScript, React y Next.js."
ImgURL = "/img/profile.jpg"

[InfoBio]
Title = "Sobre mí"
Introduction = "¡Hola! Soy Alex Navia Santos, un desarrollador de backend con un talento especial para Golang, Java y la creación de interfaces web elegantes usando HTML con Tailwind CSS. Mi enfoque está en construir backends eficientes y escalables en Spring Boot. Comprometido con el aprendizaje continuo, me esfuerzo por mejorar mis habilidades para estar a la vanguardia de las tecnologías de backend."

[[InfoBio.SkillCategories]]
Title = "Lenguajes"
IconURL= "/img/icons/golang.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Go"
IconURL= "/img/icons/golang.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Java"
IconURL= "/img/icons/java.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Html"
IconURL= "/img/icons/html.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "CSS"
IconURL= "/img/icons/css.svg"

[[InfoBio.SkillCategories]]
Title = "Frameworks"
[[InfoBio.SkillCategories.Skills]]
Name= "Spring"
IconURL= "/img/icons/spring.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Tailwind"
IconURL= "/img/icons/tailwind.svg"

[[InfoBio.SkillCategories]]
Title = "Stack Tecnológico"
[[InfoBio.SkillCategories.Skills]]
Name= "Git"
IconURL= "/img/icons/git.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Docker"
IconURL= "/img/icons/docker.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Neovim"
IconURL= "/img/icons/neovim.svg"

[[NavItems]]
Name = "Experiencia"
Id = "experience"
[[NavItems]]
Name = "Proyectos"
Id = "projects"
[[NavItems]]
Name = "Homelab"
Id = "homelab"

[[Experiences]]
Name = "Alvea"
Date = "Julio, 2023"
Position = "Desarrollador de backend senior"
Description = "Apasionado de crear increíbles experiencias web. Disfruto de convertir ideas en realidad. Tengo experiencia trabajando con JavaScript, React y Next.js."
PresentDesc = "Actualidad"
[[Experiences]]
Name = "Cleverpy"
Date = "Febrero, 2023"
Position = "Desarrollador de backend senior"
Description = "Apasionado de crear increíbles experiencias web. Disfruto de convertir ideas en realidad. Tengo experiencia trabajando con JavaScript, React y Next.js."
[[Experiences]]
Name = "Capgemini"
Date = "Enero, 2021"
Position = "Desarrollador de Backend Junior"
Description = "Apasionado de crear increíbles experiencias web. Disfruto de convertir ideas en realidad. Tengo experiencia trabajando con JavaScript, React y Next.js."

[[Projects]]
Title = "Portfolio"
Description = "Este es el sitio web de portafolio de Alex Navia. Actualmente estoy trabajando en él."
Languages = ["HTML", "Tailwind", "Go"]
[[Projects]]
Title = "HTML"
Description = "Esta es una descripción"
Languages = ["HTML", "Tailwind", "Go"]
[[Projects]]
Title = "Tailwind"
Description = "Esta es una descripción"
Languages = ["HTML", "Tailwind", "Go"]

[[HomelabItems]]
Title = "Título"
Description = "Una plataforma de almacenamiento y colaboración en la nube autoalojada usando NextCloud y otras herramientas de código abierto."
ImgURL = "/img/homelab/HomeAssistant.svg"
[[HomelabItems]]
Title = "Título"
Description = "Una plataforma de almacenamiento y colaboración en la nube autoalojada usando NextCloud y otras herramientas de código abierto."
ImgURL = "/img/homelab/HomeAssistant.svg"
[[HomelabItems]]
Title = "Título"
Description = "Una plataforma de almacenamiento y colaboración en la nube autoalojada usando NextCloud y otras herramientas de código abierto."
ImgURL = "/img/homelab/HomeAssistant.svg"
[[HomelabItems]]
Title = "Título"
Description = "Una plataforma de almacenamiento y colaboración en la nube autoalojada usando NextCloud y otras herramientas de código abierto."
ImgURL = "/img/homelab/HomeAssistant.svg"
[[HomelabItems]]
Title = "Título"
Description = "Una plataforma de almacenamiento y colaboración en la nube autoalojada usando NextCloud y otras herramientas de código abierto."
ImgURL = "/img/homelab/HomeAssistant.svg"
