[Profile]
Name = "Alex Navia"
JobTitle = "Software Developer"
Bio = "Backend developer with 4 years of experience in Java, Spring Boot, and Golang. Passionate about leveraging technology to develop innovative solutions for both business and personal challenges."
ImgURL = "/img/profile.jpg"

[InfoBio]
Title = "About"
Introduction = "Hi there! I'm a backend developer with a strong foundation in Golang, Java, and web interfaces. My focus is on building efficient, scalable backends using a variety of modern tools and technologies. I have extensive experience with relational databases, CI/CD processes, and container orchestration. My toolkit includes Jenkins, Openshift, SonarQube for testing and quality assurance, and Docker for deployment."
Expanded = """
Here are some of the key technologies and tools I use:

- Languages and Frameworks:

    - Java and Spring Boot: For developing robust and scalable applications.
    - Golang: For high-performance, concurrent applications.
    - HTML and Tailwind CSS: For creating clean, responsive web interfaces.

- Databases:

    - Relational Databases: Experienced with MySQL, PostgreSQL for handling structured data efficiently.

- CI/CD and Deployment:

    - Jenkins: For continuous integration and continuous deployment, ensuring smooth and automated delivery pipelines.
    - Openshift: For managing containerized applications and orchestrating deployments.
    - Docker: For containerization, facilitating scalable and portable application deployment.
    - SonarQube: For testing and maintaining code quality, ensuring high standards in all my projects.
- Testing and Quality Assurance:

    - Mockito: For creating mock objects and writing unit tests.
    - Postman: For testing API endpoints and ensuring reliable integrations.
"""

[[InfoBio.SkillCategories]]
Title = "Languages"
IconURL= "/img/icons/golang.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Go"
IconURL= "/img/icons/golang.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Java"
IconURL= "/img/icons/java.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Html"
IconURL= "/img/icons/html.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "CSS"
IconURL= "/img/icons/css.svg"

[[InfoBio.SkillCategories]]
Title = "Frameworks"
[[InfoBio.SkillCategories.Skills]]
Name= "Spring"
IconURL= "/img/icons/spring.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Tailwind"
IconURL= "/img/icons/tailwind.svg"

[[InfoBio.SkillCategories]]
Title = "Tech Stack"
[[InfoBio.SkillCategories.Skills]]
Name= "Git"
IconURL= "/img/icons/git.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Docker"
IconURL= "/img/icons/docker.svg"
[[InfoBio.SkillCategories.Skills]]
Name= "Neovim"
IconURL= "/img/icons/neovim.svg"

[[NavItems]]
Name = "Projects"
Id = "projects"
[[NavItems]]
Name = "Experience"
Id = "experience"
[[NavItems]]
Name = "Homelab"
Id = "homelab"

[[Experiences]]
Name = "Alvea, Accenture"
Date = "July, 2023"
Position = "Senior backend developer"
Description = "In my current role, I develop backend systems for Santander Bank using Java and Spring, focusing on creating orchestrators and microservices from scratch. I manage containerization with OpenShift and handle routes and gateways. Additionally, I implement CI/CD pipelines with Jenkins, overseeing releases and deployments to certification and pre-production environments. My work involves collaborating with both relational and non-relational databases to support diverse data requirements."
PresentDesc = "Present"
[[Experiences]]
Name = "Cleverpy"
Date = "February, 2023"
Position = "Senior backend developer"
Description = "In this role, I developed REST APIs using Spring Boot, JPA, and PL/SQL, adapting other backend tools as required by the project. I was responsible for project configuration and maintenance, gaining experience in both hexagonal and multi-layer architectures."
[[Experiences]]
Name = "Capgemini"
Date = "January, 2021"
Position = "Junior Backend Developer"
Description = "During this period, I developed REST APIs and worked extensively with Spring Boot, JPA, and PL/SQL. I utilized various tools such as Jenkins, Kibana, Postman, JUnit 5, Mockito, RestAssured, and Lombok. Additionally, I supervised and supported junior developers, ensuring their integration and growth within the team."

[[Projects]]
Title = "Portfolio"
Description = "Developed a portfolio website to showcase my skills and projects, featuring a user-friendly interface with HTML, HTMX, and Tailwind CSS, and a Go backend for performance. Includes sections for work experience, side-projects, and my homelab websites, with responsive design for all devices. Integrates theme changes and language adjustments without using JavaScript at all. Linked with GitHub and LinkedIn for a comprehensive profile."
Link = "https://github.com/alnav3/portfolio"
Languages = ["HTMX", "Tailwind", "Go", "Dockerfile"]
[[Projects]]
Title = "Split website"
Description = "Developing SplitWeb, an open-source alternative to Splitwise, ensuring complete data encryption and privacy. Each user's data is fully encrypted with their personal key, inaccessible to anyone else, including the administrator. Using Turso for the database, SplitWeb is fully self-hostable, supporting both personal Turso keys and local SQLite databases. This project offers a secure and private solution for managing shared expenses."
Link = "https://github.com/alnav3/splitweb"
Languages = ["HTMX", "Tailwind", "Go", "Turso", "LibSQL", "Dockerfile"]
[[Projects]]
Title = "Dotfiles"
Description = "Maintaining a comprehensive set of dotfiles to set up my working environment from scratch and serve as a backup of all my configurations. The project uses GNU Stow to manage configuration files in a single place and includes my configurations for Neovim, Tmux, and Zsh. It also features a Nix environment backup with all required packages and a bash script for automatic installation, allowing me to start working on any computer within minutes."
Link = "https://github.com/alnav3/dotfiles"
Languages = ["lua", "shell", "config"]
[[Projects]]
Title = "ZMK Configuration"
Description = "Custom ZMK configuration for my split keyboard to meet my specific needs and optimize workflow. Enhances productivity by customizing key mappings and macros tailored to my requirements."
Link = "https://github.com/alnav3/zmk-config"
Languages = [ "C" ]
[[Projects]]
Title = "Gitproject"
Description = "A ChatGPT plugin written in Go, designed for simple interaction with GitHub repositories. Enhances ChatGPT applications by fetching repository information, searching for files, and identifying issues directly within the code."
Link = "https://github.com/alnav3/gitplugin"
Languages = [ "Go", "Dockerfile" ]

[[HomelabItems]]
Title = "Proxmox"
Description = "A powerful virtualization platform I use to manage VMs and containers, allowing me to deploy and test various systems efficiently."
ImgURL = "/img/homelab/proxmox.png"
[[HomelabItems]]
Title = "Coolify"
Description = "My go-to platform for deploying personal projects and Docker containers, providing a self-hosted alternative to cloud services."
ImgURL = "/img/homelab/coolify.png"
Link = "https://coolify.alnav.dev/"
[[HomelabItems]]
Title = "Penpot"
Description = "An open-source design tool I use for prototyping web projects, enhancing my development workflow from concept to implementation."
ImgURL = "/img/homelab/penpot.svg"
Link = "https://penpot.alnav.dev/"
[[HomelabItems]]
Title = "Gitea"
Description = "A lightweight, self-hosted Git service for managing my project repositories and version control needs."
ImgURL = "/img/homelab/gitea.png"
Link = "https://git.alnav.dev/"
[[HomelabItems]]
Title = "Home Assistant"
Description = "An open-source platform I use to automate and control smart home devices, creating a centralized IoT ecosystem."
ImgURL = "/img/homelab/HomeAssistant.svg"

