[Profile]
Name = "Alex Navia"
JobTitle = "Desarrollador de Software"
Bio = "Desarrollador backend con 4 años de experiencia en Java, Spring Boot y Golang. Apasionado por la tecnología y por crear soluciones innovadoras a problemas empresariales y personales."
ImgURL = "/img/profile.jpg"

[InfoBio]
Title = "Sobre mí"
Introduction = "¡Hola! Soy un desarrollador backend con una sólida experiencia en Golang, Java y la creación de interfaces web. Me enfoco en construir backends eficientes y escalables utilizando una variedad de herramientas y tecnologías modernas. Tengo amplia experiencia con bases de datos relacionales, procesos CI/CD y orquestación de contenedores. Mi conjunto de herramientas incluye Jenkins, Openshift, SonarQube para pruebas y control de calidad, y Docker para despliegues."

[[InfoBio.SkillCategories]]
Title = "Lenguajes"
IconURL = "/img/icons/golang.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "Go"
IconURL = "/img/icons/golang.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "Java"
IconURL = "/img/icons/java.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "Html"
IconURL = "/img/icons/html.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "CSS"
IconURL = "/img/icons/css.svg"

[[InfoBio.SkillCategories]]
Title = "Frameworks"
[[InfoBio.SkillCategories.Skills]]
Name = "Spring"
IconURL = "/img/icons/spring.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "Tailwind"
IconURL = "/img/icons/tailwind.svg"

[[InfoBio.SkillCategories]]
Title = "Stack Tecnológico"
[[InfoBio.SkillCategories.Skills]]
Name = "Git"
IconURL = "/img/icons/git.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "Docker"
IconURL = "/img/icons/docker.svg"
[[InfoBio.SkillCategories.Skills]]
Name = "Neovim"
IconURL = "/img/icons/neovim.svg"

[[NavItems]]
Name = "Proyectos"
Id = "projects"
[[NavItems]]
Name = "Experiencia"
Id = "experience"
[[NavItems]]
Name = "Homelab"
Id = "homelab"

[[Experiences]]
Name = "Alvea, Accenture"
Date = "Julio, 2023"
Position = "Desarrollador de backend senior"
Description = "En mi rol actual, desarrollo sistemas backend para el Banco Santander utilizando Java y Spring, enfocándome en la creación de orquestadores y microservicios desde cero. Gestiono la modificación de contenedores con OpenShift y manejo rutas y gateways. Además, implemento pipelines de CI/CD con Jenkins, supervisando las versiones y despliegues a entornos de certificación y preproducción. Mi posición implica trabajar con bases de datos relacionales y no relacionales para satisfacer diversas necesidades de datos."
PresentDesc = "Actualidad"
[[Experiences]]
Name = "Cleverpy"
Date = "Febrero, 2023"
Position = "Desarrollador de backend senior"
Description = "En este rol, desarrollé APIs REST utilizando Spring Boot, JPA y PL/SQL, adaptando otras herramientas backend según lo requerido por el proyecto. Fui responsable de la configuración y mantenimiento de proyectos, ganando experiencia en arquitecturas hexagonales y de múltiples capas."
[[Experiences]]
Name = "Capgemini"
Date = "Enero, 2021"
Position = "Desarrollador de Backend Junior"
Description = "Desarrollo de APIs REST trabajando con Spring Boot, JPA y PL/SQL. Utilización de herramientas como Jenkins, Kibana, Postman, JUnit 5, Mockito, RestAssured y Lombok. Supervisión y apoyo a desarrolladores junior."

[[Projects]]
Title = "Portfolio"
Description = "He desarrollado un sitio web de portafolio para mostrar mis habilidades y proyectos, con una interfaz fácil de usar construida con HTML, HTMX y Tailwind CSS, y un backend en Go para un mejor rendimiento. Incluye secciones para experiencia laboral, proyectos personales y mis sitios web de homelab, con diseño responsivo para todos los dispositivos. Integra cambios de tema y ajustes de idioma sin usar nada de JavaScript. Vinculado con GitHub y LinkedIn para un perfil profesional completo."
Link = "https://github.com/alnav3/portfolio"
Languages = ["HTMX", "Tailwind", "Go", "Dockerfile"]
[[Projects]]
Title = "Split website"
Description = "Estoy desarrollando SplitWeb, una alternativa de código abierto a Splitwise, que garantiza la completa encriptación y privacidad de los datos. La información de cada usuario está totalmente encriptada con su propia clave personal y no es accesible para nadie más, ni siquiera para el administrador. Usando Turso como base de datos, SplitWeb se puede desplegar en tu propio servidor, permitiendo el uso de claves personales de Turso o bases de datos locales SQLite. Este proyecto ofrece una solución segura y privada para gestionar gastos compartidos."
Link = "https://git.alnav.dev/alnav3/splitweb"
Languages = ["HTMX", "Tailwind", "Go", "Turso", "LibSQL", "Dockerfile"]
[[Projects]]
Title = "Dotfiles"
Description = "Mantenimiento de un conjunto completo de dotfiles para configurar mi entorno de trabajo desde cero y servir como backup de todas mis configuraciones. El proyecto utiliza GNU Stow para gestionar los archivos de configuración en un solo lugar e incluye mis configuraciones para Neovim, Tmux y Zsh. También cuenta con una copia de seguridad del entorno Nix con todos los paquetes necesarios y un script bash para la instalación automática, permitiéndome empezar a trabajar en cualquier ordenador en minutos."
Link = "https://github.com/alnav3/dotfiles"
Languages = ["lua", "shell", "config"]
[[Projects]]
Title = "Configuración ZMK"
Description = "Configuración personalizada de ZMK para mi teclado Aurora Corne, adaptada a mis necesidades específicas y optimizar mi flujo de trabajo. Mejora mi productividad personalizando las asignaciones de teclas y macros."
Link = "https://github.com/alnav3/zmk-config"
Languages = ["C"]
[[Projects]]
Title = "Gitplugin"
Description = "Un plugin para ChatGPT escrito en Go, diseñado para interactuar fácilmente con repositorios de GitHub. Mejora las aplicaciones de ChatGPT obteniendo información del repositorio, buscando archivos y detectando problemas directamente en el código."
Link = "https://github.com/alnav3/gitplugin"
Languages = ["Go", "Dockerfile"]

[[HomelabItems]]
Title = "Proxmox"
Description = "Potente hypervisor que utilizo para gestionar máquinas virtuales, permitiéndome desplegar y probar sistemas operativos de manera eficiente."
ImgURL = "/img/homelab/proxmox.png"
[[HomelabItems]]
Title = "Coolify"
Description = "Mi plataforma preferida para desplegar proyectos personales y contenedores Docker, proporcionando una alternativa autoalojada a los servicios en la nube."
ImgURL = "/img/homelab/coolify.png"
[[HomelabItems]]
Title = "Penpot"
Description = "Una herramienta de diseño open source que utilizo para diseñar proyectos web, mejorando mi flujo de trabajo para proyectos front."
ImgURL = "/img/homelab/penpot.svg"
[[HomelabItems]]
Title = "Gitea"
Description = "Un servicio Git ligero y open source para gestionar mis repositorios de proyectos y necesidades de control de versiones."
ImgURL = "/img/homelab/gitea.png"
[[HomelabItems]]
Title = "Home Assistant"
Description = "Una plataforma de código abierto que utilizo para automatizar y controlar dispositivos inteligentes del hogar, creando un ecosistema IoT centralizado."
ImgURL = "/img/homelab/HomeAssistant.svg"
[[HomelabItems]]
Title = "Uptime Kuma"
Description = "Una herramienta de monitoreo de webs que uso para asegurar el correcto funcionamiento de mis servicios y un rendimiento óptimo."
ImgURL = "/img/homelab/uptime-kuma.webp"
Link = "https://uptime.alnav.dev/"

